import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const jose = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Todo Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jose.className} h-screen bg-very-dark-blue`}>
        {children}
      </body>
    </html>
  );
}
